name: Bug report
description: Report something that is broken or incorrect
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        **Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: repex
    attributes:
      label: Minimal reproducible example
      description: A code snipped that we can copy&paste to reproduce the bug without having any data
      render: python
      placeholder: |
        import scirpy as ir
        adata = ir.datasets.wu2020_3k()

        ir.do_something_that_doesnt_work(adata)

  - type: textarea
    id: stacktrace
    attributes:
      label: The error message produced by the code above
      description: Please paste the entire error message
      render: pytb
      placeholder: |
        ---------------------------------------------------------------------------
        AssertionError                            Traceback (most recent call last)
        <ipython-input-5-78750baef17a> in <module>
        ----> 1 adata = ir.io.read_airr(
              2 ["/home/data/scirpy/OUT_igblast-1-17-1.tsv"]
              3 )

        /opt/conda/lib/python3.8/site-packages/scirpy/io/_io.py in read_airr(path, use_umi_count_col, infer_locus, cell_attributes, include_fields)
            437             tmp_cell.add_chain(chain_dict)
            438
        --> 439     return from_airr_cells(airr_cells.values(), include_fields=include_fields)
            440
            441

  - type: textarea
    id: versions
    attributes:
      label: Version information
      description: |
        Please paste the output of `scanpy.logging.print_versions()` here.
      placeholder: |
        scirpy: 0.7.0
        numpy: 1.22.3
        pandas: 1.4.2
        AnnData: 0.7.6
        Python: 3.7
        OS: Arch Linux
