{% set name = "scirpy" %}
{% set version = "develop" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ".."

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip!=22.1 # https://github.com/pypa/pip/issues/11110
    - flit
    - setuptools_scm
    - pytoml
    - importlib_metadata

  run:
    - python >=3.7
    - anndata >=0.7.6
    - scanpy >=1.6.0
    - pandas >=1.0
    - numpy >=1.17.0
    - scipy
    - parasail-python
    - scikit-learn
    - python-levenshtein
    - python-igraph !=0.10.0,!=0.10.1
    - adjusttext >=0.7
    - networkx >=2.5
    - squarify
    - tqdm >=4.44.1
    - airr >=1.2
    - numba >=0.41.0

test:
  source_files:
    - docs
  requires:
    - pytest
    - leidenalg
    - jupytext
    - pycairo
    - jupyter_client
    - ipykernel
    - nbconvert
  imports:
    - scirpy
  commands:
    - pytest --pyargs scirpy -m "not extra"
    - cd docs && jupytext --execute tutorials/tutorial_3k_tcr.md

about:
  home: https://scverse.org/scirpy
  dev_url: https://github.com/scverse/scirpy
  license: BSD-3
  license_family: BSD
  summary: A Scanpy extension for analyzing single-cell T-cell receptor sequencing data.

extra:
  identifiers:
   - doi:10.1101/2020.04.10.035865
