{% set name = "scirpy" %}
{% set version = "develop" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ".."

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"

requirements:
  # The way the version is resolved from SCM (flit + get_version)
  # requires all dependencies to be installed at build time. 
  host:
    - python >=3.6
    - flit
    - get_version
    - anndata >=0.7.1
    - scanpy>=1.4.6
    - pandas>=0.21
    - numpy=1.18
    - scipy
    - parasail-python
    - scikit-learn
    - python-levenshtein
    - python-igraph
    - networkx
    - squarify
  run:
    - python >=3.6
    - get_version
    - anndata >=0.7.1
    - scanpy>=1.4.6
    - pandas>=0.21
    - numpy
    - scipy
    - parasail-python
    - scikit-learn
    - python-levenshtein
    - python-igraph
    - networkx
    - squarify

test:
  requires:
    - pytest
    - sphinx>=3.0.1
    - sphinx-autodoc-typehints>=1.8.0
    - sphinx_rtd_theme>=0.4
    - leidenalg
    - nbsphinx >= 0.6.0
    - jupytext
    - sphinxcontrib-bibtex>=1.0.0
    - pycairo
    - jupyter_client
    - ipykernel
    - squarify
    - pip:
       - scanpydoc>=0.4.5
       - 'typing_extensions; python_version < "3.8"',  # for `Literal`
  imports:
    - scirpy
  commands:
    - pytest
    - cd docs && make html SPHINXOPTS="-W --keep-going"

about:
  home: https://icbi-lab.github.io/scirpy
  dev_url: https://github.com/icbi-lab/scirpy 
  license: BSD-3
  license_family: BSD
  summary: A Scanpy extension for analyzing single-cell T-cell receptor sequencing data.  

extra:
  identifiers:
   - doi:10.1101/2020.04.10.035865  
