{% set name = "scirpy" %}
{% set version = "develop" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ".."

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"

requirements:
  # The way the version is resolved from SCM (flit + get_version)
  # requires all dependencies to be installed at build time.
  host:
    - python >=3.6
    - flit
    - setuptools_scm
    - pytoml
    - importlib_metadata

  run:
    - python >=3.6
    - anndata >=0.7.3
    - scanpy>=1.5.1
    - pandas>=0.21
    - numpy
    - scipy
    - parasail-python
    - scikit-learn
    - python-levenshtein
    - python-igraph
    - networkx
    - squarify
    - tqdm>=4.29.1
    - airr>=1.2

test:
  source_files:
    - tests
    - docs
  requires:
    - pytest
    - leidenalg
    - jupytext
    - pycairo
    - jupyter_client
    - ipykernel
    - nbconvert
  imports:
    - scirpy
  commands:
    - pytest
    - cd docs && jupytext --execute tutorials/tutorial_3k_tcr.md

about:
  home: https://icbi-lab.github.io/scirpy
  dev_url: https://github.com/icbi-lab/scirpy
  license: BSD-3
  license_family: BSD
  summary: A Scanpy extension for analyzing single-cell T-cell receptor sequencing data.

extra:
  identifiers:
   - doi:10.1101/2020.04.10.035865
