package:
  name: scirpy
  version: develop

source:
  path: ".."

build:
  number: 0
  noarch: python
  script: python -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.12
    - pip
    - hatchling
    - hatch-vcs

  run:
    - python >=3.12
    - anndata >=0.9
    - awkward >=2.1.0
    - mudata >=0.2.3
    - scanpy >=1.9.3
    - pandas >=2.3.0
    - numpy >=1.17.0
    - scipy
    - scikit-learn
    - python-levenshtein
    - python-igraph !=0.10.0,!=0.10.1
    - networkx >=2.5
    - squarify
    - airr >=1.2
    - tqdm >=4.63
    - adjusttext >=0.7
    - numba >=0.41.0
    - pooch >=1.7.0
    - joblib >=1.3.1
    - logomaker !=0.8.5

tests:
  - python:
      imports:
        - scirpy
  - script:
      - pytest --pyargs scirpy -m "not extra and not gpu"
    requirements:
      run:
        - pytest
        - leidenalg
        - jupytext
        - pycairo
        - jupyter_client
        - ipykernel
        - nbconvert
        - muon >=0.1.5
    files:
      source:
        - docs

about:
  homepage: https://scirpy.scverse.org
  repository: https://github.com/scverse/scirpy
  license: BSD-3-Clause
  summary: A Scanpy extension for analyzing single-cell T-cell receptor sequencing data.

extra:
  identifiers:
    - doi:10.1101/2020.04.10.035865
