name: conda

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0} # -l for login shell (conda), -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.14"

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda
          channel-priority: strict
          python-version: ${{ matrix.python }}

      - name: install rattler-build
        run: |
          mamba install -y rattler-build python=${{ matrix.python }}

      - name: build and test package
        run: |
          cd .conda && rattler-build build -c conda-forge -c bioconda
