name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 1,15 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.9"
          - os: ubuntu-latest
            python: "3.11"
          - os: ubuntu-latest
            python: "3.11"
            pip-flags: "--pre"
            name: PRE-RELEASE DEPENDENCIES

    name: ${{ matrix.name }} Python ${{ matrix.python }}

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel
      - name: Install dependencies
        run: |
          # Workaround issue with scikit-bio
          # This will work in the next release, see https://github.com/biocore/scikit-bio/pull/1813
          pip install git+https://github.com/grst/scikit-bio.git@main
          pip install ${{ matrix.pip-flags }} ".[dev,test,rpack,dandelion]"
      - name: Test
        env:
          MPLBACKEND: agg
          PLATFORM: ${{ matrix.os }}
          DISPLAY: :42
        run: |
          coverage run -m pytest -v --color=yes
      - name: Report coverage
        run: |
          coverage report
      - name: Upload coverage
        uses: codecov/codecov-action@v3
